-- SHOW EMPLOYEE NAME, MANAGERS NAME WHICH MATCHES SAME ID WITH SELF JOIN
SELECT e.FIRST_NAME, m.FIRST_NAME
FROM EMPLOYEES AS e
	JOIN EMPLOYEES AS m
    ON e.EMPLOYEE_ID = m.MANAGER_ID;
-- THOSE DEPARTMENTS WHICH DEPARTMENT HAS NO EMPLOYEES
SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES
		ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;
-- EMP FIRSTNAME, SALARY, SALARY LESS THAN AVG DEPT SALARY

SELECT
	   EMPLOYEES.FIRST_NAME,
       EMPLOYEES.SALARY,
       (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID) - EMPLOYEES.SALARY -- AVG SALARY OF EACH DEPT
FROM EMPLOYEES 
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
-- THOSE DEPARTMENT NAME WHERE MINIMUM SALARY > 5000
SELECT DEPARTMENT_NAME, MIN(SALARY), AVG(SALARY)
FROM EMPLOYEES
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING MIN(SALARY) > 5000;

