USE DUMMYDB;
-- UNION
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 10000
UNION
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- INTERSECTION
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 10000
INTERSECT
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;
-- MINUS OPS BUT MYSQL DOESNOT SUPPORT MINUS OPS
SELECT * 
FROM EMPLOYEES
WHERE SALARY > 10000
MINUS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;