-- WHAT IS THE SECOND HIGHEST SALARY? AND WHOM GET THE SALARY?
USE DUMMYDB;
SELECT SALARY AS SECOND_HIGHEST_SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1
OFFSET 1;
-- 
SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT SALARY AS SECOND_HIGHEST_SALARY
				FROM EMPLOYEES
				ORDER BY SALARY DESC
				LIMIT 1
				OFFSET 1);
-- SECOND WAY
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
				FROM EMPLOYEES);
--
SELECT *
FROM EMPLOYEES 
WHERE SALARY = (SELECT MAX(SALARY)
				FROM EMPLOYEES
				WHERE SALARY < (SELECT MAX(SALARY)
								FROM EMPLOYEES));
-- THOSE EMPLOYEES GET THE SALARY GRETER THAN MANAGER
SELECT * 
FROM EMPLOYEES AS EMP
WHERE SALARY > (SELECT SALARY
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID
                );
-- THOSE EMPLOYEES DO THE SAME JOB AS MANAGER
SELECT * 
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (SELECT JOB_ID
				FROM EMPLOYEES AS MGR
                WHERE EMP.EMPLOYEE_ID = MGR.EMPLOYEE_ID);