-- EXAMPLE 1
USE DUMMYDB;
WITH AVGIT AS
( 	  SELECT AVG(SALARY) AS SAL1
	  FROM EMPLOYEES
	  WHERE DEPARTMENT_ID = 60 -- IT
),
MARKT AS
(	SELECT MAX(SALARY) AS SAL2
	FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 20 -- MARKETING
)
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL1 FROM AVGIT) AND SALARY < (SELECT SAL2 FROM MARKT);
